<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Romlig analyse av boligpriser i King County</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="arbeidskrav_files/libs/clipboard/clipboard.min.js"></script>
<script src="arbeidskrav_files/libs/quarto-html/quarto.js"></script>
<script src="arbeidskrav_files/libs/quarto-html/popper.min.js"></script>
<script src="arbeidskrav_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="arbeidskrav_files/libs/quarto-html/anchor.min.js"></script>
<link href="arbeidskrav_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="arbeidskrav_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="arbeidskrav_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="arbeidskrav_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="arbeidskrav_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="arbeidskrav_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="arbeidskrav_files/libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Romlig analyse av boligpriser i King County</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduksjon" class="level1">
<h1><strong>1.0 Introduksjon</strong></h1>
<p>I denne oppgaven skal vi analysere boligmarkedet i King County i USA, med fokus på ulike faktorer som påvirker boligprisene. Først vil vi gjennomføre en <em>Exploratory Data Analysis (EDA)</em> i GeoDa for å undersøke romlig autokorrelasjon mellom pris og boareal, samt forsøke å kartlegge hvor ulike boligtyper er lokalisert. Videre i oppgaven vil vi estimere tre ulike hedoniske prismodeller for å undersøke hvordan både huskarkateristika og områdespesifikke variabler påvirker salgsprisene. Videre vil vi fastslå «spatial effects» og fortsette med «spatial regressions» for å forsøke å forstå hvordan geografiske forskjeller og nabolagskarakteristika bidrar til variasjoner i boligpriser. Vi skal bruke metodene til både <span class="citation" data-cites="anselin1988">Anselin (<a href="#ref-anselin1988" role="doc-biblioref">1988</a>)</span> og <span class="citation" data-cites="lesage">LeSage (<a href="#ref-lesage" role="doc-biblioref">n.d.</a>)</span> for å fastslå hvilken romlig regresjonsmodell som best fanger opp de romlige effektene.<br>
</p>
</section>
<section id="data" class="level1">
<h1><strong>2.0 Data</strong></h1>
<section id="house-sales-in-king-county-usa" class="level2">
<h2 class="anchored" data-anchor-id="house-sales-in-king-county-usa">2.1 House Sales in King County, USA</h2>
<p>Det første datasettet vi har brukt i oppgaven er <em>House Sales in King County, USA</em> fra Kaggle. Datasettet inneholder rundt 27 000 observasjoner med detaljerte variabler som beskriver ulike egenskaper ved de solgte boligene. I tillegg inneholder datasettet salgspris og geografiske koordinater for hver observasjon. Variablene gir en omfattende innsikt i både boligkarakteristika og salgsdetaljer for perioden 2014-2015. Vi la til en variabel som angir avstand i km til CBD i Seattle og endret kartprojeksjonen til EPSG 2926.</p>
</section>
<section id="wadoh-environmental-health-disparities-index-calculated-for-king-county" class="level2">
<h2 class="anchored" data-anchor-id="wadoh-environmental-health-disparities-index-calculated-for-king-county">2.2 WADOH Environmental Health Disparities Index Calculated for King County</h2>
<p>I datsettet <em>House Sales in King County, USA</em> fra Kaggle mangler det variabler som beskriver området hvor boligene ligger. Denne informasjonen henter vi fra datasettet <em>WADOH Environmental Health Disparities Index calculated for King County</em>, utarbeidet av Washington State Department of Health. Datasettet inneholder en EHD-indeks, og de variablene som denne indeksen er utarbeidet fra, for alle “cencus tracts” i King County. Vi endret også projeksjonen på dette kartet til EPSG 2926.</p>
</section>
<section id="cencus-shapefile-og-tracts10" class="level2">
<h2 class="anchored" data-anchor-id="cencus-shapefile-og-tracts10">2.3 Cencus shapefile og tracts10</h2>
<p>Vi benyttet også flere datasett fra en cencus shapefil for King County, utarbeidet av King County GIS. Vi hentet data om samlet familie inntekt fra datafilen <em>acs_b19101_familyincome.dbf</em> og opplysninger om etnisitet fra datasettet <em>acs_b02001_race.dbf.</em> Disse to datasettene gir informasjon om familie inntekt og etnisitet på “cencus-tracts”-nivå. Vi brukte disse to datasettene til å lage variabler som vi la til i WADOH-datasettet. Fra cencus shapefilen lastet vi også ned kartet <em>tracts10</em>. Vi la variablene fra WADOH-datasettet in i <em>tracts10</em>. Videre gjorde vi en spatial join med hus-datene fra Kaggle for å binde områdevariablene til de respektive boligene. Vi benyttet projeksjonen EPSG 2926 for alle kartene.</p>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level1">
<h1><strong>3.0 Exploratory Data Analysis (EDA)</strong></h1>
<p>Vi har gjennomført en Exploratory Data Analysis (EDA) av dataene i Geoda. Her har vi generert en vektfil ut fra 3 og 10 nærmeste naboer og brukt <em>Bivariate Moran`s I</em> til å undersøke romlig autokorrelasjon mellom pris og boareal (sqft_living). Vi har også brukt <em>Bivariate Local Morans I</em> for å finne ut hvor de små og dyre, store og dyre, billige og store, og de små og billige boligene ligger.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-1" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Skjermbilde%202024-11-05%20kl.%2011.11.56.png" class="img-fluid figure-img" width="716">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Bivariate Moran’s I for pris og boareal (sqft_living) med 3 og 10 nærmeste naboer
</figcaption>
</figure>
</div>
</div>
</div>
<p>I <a href="#fig-1" class="quarto-xref">Figure&nbsp;1</a> ovenfor ser vi at Bivariate Moran’s I har en verdi på 0.406 for de 3 nærmeste naboene og en noe lavere verdi på 0.353 når vi utvidet til de 10 nærmeste naboene. Begge verdiene er positive, noe som indikerer en romlig autokorrelasjon mellom pris og boareal (sqft_living). Dette innebærer at boliger med høy pris har en tendens til å ligge nær andre boliger med høyt boareal, mens boliger med lav pris har en tendens til å ligge nær boliger med lavt boareal. At autokorrelasjonen avtar noe når vi utvider antall naboer, kan tyde på at sammenhengen mellom pris og boareal er sterkest lokalt. Dette antyder at relasjonen mellom pris og boareal er mer markant i nærområder, men svekkes over lengre avstander.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-2" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/Skjermbilde%202024-11-05%20kl.%2012.04.41.png" class="img-fluid figure-img" width="635">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Bivariate Local Moran’s I for pris og boareal (sqft_living) med 3 og 10 nærmeste naboer illustrert ved LISA Cluster map
</figcaption>
</figure>
</div>
</div>
</div>
<p>I <a href="#fig-2" class="quarto-xref">Figure&nbsp;2</a> har vi brukt <em>Bivariate Local Morans I</em> for å finne ut hvor de små og dyre, store og dyre, store og billige, og de små og billige boligene ligger. Dette illustreres ved hjelp av et LISA cluster map. Kartet til venstre viser fordelingen for 3 nærmeste naboer, mens kartet til høyre viser fordelingen for 10 nærmeste naboer. De to kartene er relativt like og vi kan se lignende mønster. Ut i fra disse kartene er det tydelig at for både 3 og 10 nærmeste naboer er store og dyre boliger er konsentrert nord i King County, det samme gjelder for små og dyre boliger. Dette reflekterer “hot spots” hvor dyre boliger samles. Det kommer også frem fra kartene at det er flere store og dyre boliger enn det er små og dyre boliger. Når det kommer til billige boliger, er disse mer jevnt fordelt enn de dyre. Sør i King County er det overvekt av billige boliger. Store og billige, samt små og billige boliger er utbredt i sør, noe som kan tyde på “cold spots” hvor fattige eller mindre attraktive nabolag er utbredt.</p>
</section>
<section id="hedoniske-modeller" class="level1">
<h1><strong>4.0 Hedoniske modeller</strong></h1>
<p>Hedoniske modeller brukes for å estimere boligpriser basert på spesifikke egenskaper som boligens størrelse, beliggenhet, nærhet til fasiliteter, samt miljømessige kvaliteter som luftkvalitet og støy. Ved å analysere hvordan disse faktorene påvirker salgspriser, kan vi finne den implisitte prisen av hver egenskap. Vi skal i dette kapittelet definere tre hedoniske modeller.</p>
<p>Den første modellen er en null modell med bare huskarakteristika og tids-dummier. Den andre modellen inkluderer huskarakteristika, distanse til CBD, relevante tract-variabler (transport og poverty) og tids-dummier. Den tredje modellen inkluderer huskarakteristika, distanse til CBD, EHD indeks og tids-dummier.</p>
<ol type="1">
<li><span class="math inline">\(P_i = \beta_0 + \beta_1 \cdot \text{bedrooms}_i + \beta_2 \cdot \text{bathrooms}_i + \beta_3 \cdot \text{sqft\_living}_i + \beta_4 \cdot \text{sqft\_lot}_i + \beta_5 \cdot \text{floors}_i + \beta_6 \cdot \text{year\_month}_i + \epsilon_i\)</span></li>
<li><span class="math inline">\(P_i = \beta_0 + \beta_1 \cdot \text{bedrooms}_i + \beta_2 \cdot \text{bathrooms}_i + \beta_3 \cdot \text{sqft\_living}_i + \beta_4 \cdot \text{sqft\_lot}_i + \beta_5 \cdot \text{floors}_i + \beta_6 \cdot \text{distCBD}_i + \beta_7 \cdot \text{transport}_i + \beta_8 \cdot \text{poverty}_i + \beta_{9j} \cdot \text{year\_month}_i + \epsilon_i\)</span></li>
<li><span class="math inline">\(P_i = \beta_0 + \beta_1 \cdot \text{bedrooms}_i + \beta_2 \cdot \text{bathrooms}_i + \beta_3 \cdot \text{sqft\_living}_i + \beta_4 \cdot \text{sqft\_lot}_i + \beta_5 \cdot \text{floors}_i + \beta_6 \cdot \text{distCBD}_i + \beta_7 \cdot \text{EHDindex}_i + \beta_8 \cdot \text{year\_month}_i + \epsilon_i\)</span></li>
</ol>
<section id="regresjonstabell" class="level2">
<h2 class="anchored" data-anchor-id="regresjonstabell">4.1 Regresjonstabell</h2>
<div class="cell" data-ft.arraystretch="0.9">
<div id="tbl-1" class="cell quarto-float anchored" data-ft.arraystretch="0.9">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Regresjonstabell for de tre ulike hedoniske modellene
</figcaption>
<div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-6c819e2c{}.cl-6c71fd64{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6c77a674{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6c77a688{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 0.3;background-color:transparent;}.cl-6c77d108{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6c77d11c{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6c77d11d{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-6c819e2c"><thead><tr style="overflow-wrap:break-word;"><th class="cl-6c77d108"><p class="cl-6c77a674"><span class="cl-6c71fd64"> </span></p></th><th class="cl-6c77d108"><p class="cl-6c77a674"><span class="cl-6c71fd64">Modell 1</span></p></th><th class="cl-6c77d108"><p class="cl-6c77a674"><span class="cl-6c71fd64">Modell 2</span></p></th><th class="cl-6c77d108"><p class="cl-6c77a674"><span class="cl-6c71fd64">Modell 3</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(Intercept)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">79893.490***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">845500.071***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">405315.746***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(8.118)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(31.295)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(45.066)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">bedrooms</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-59606.355***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-49195.378***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-46342.134***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-25.021)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-24.540)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-23.306)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">bathrooms</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">6795.037+</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">19338.314***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">20288.528***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(1.762)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(5.961)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(6.316)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">sqft_living</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">315.571***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">294.543***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">288.133***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(99.650)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(108.515)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(108.069)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">sqft_lot</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-0.399***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">0.428***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">0.223***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-8.770)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(10.824)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(5.704)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">floors</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-3785.107</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-22766.366***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-18888.026***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-0.992)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-7.042)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-5.948)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2014-06</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">6015.759</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">10562.394</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">11027.366</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(0.719)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(1.505)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(1.587)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2014-07</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-7287.796</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">2932.383</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">3230.760</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-0.875)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(0.420)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(0.467)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2014-08</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-2472.900</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">8832.195</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">7152.294</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-0.288)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(1.226)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(1.002)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2014-09</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-7838.399</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">2520.796</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">1669.215</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-0.892)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(0.342)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(0.229)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2014-10</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">643.829</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">7249.104</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">9102.974</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(0.074)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(0.998)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(1.265)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2014-11</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-7658.061</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-2033.165</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-178.541</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-0.822)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-0.260)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-0.023)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2014-12</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-16854.808+</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-1382.891</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-127.009</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-1.833)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-0.179)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-0.017)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2015-01</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-12714.538</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">3829.449</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">8256.888</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-1.222)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(0.439)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(0.955)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2015-02</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-12149.568</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">10768.049</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">15466.226+</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-1.262)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(1.333)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(1.933)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2015-03</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">24034.109**</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">38092.481***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">40551.732***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(2.783)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(5.258)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(5.650)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2015-04</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">29222.396***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">37461.977***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">39250.975***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(3.522)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(5.381)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(5.692)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">year_month2015-05</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">34683.499**</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">48236.175***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">51566.411***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(2.894)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(4.797)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(5.177)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">dist_cbd[, 1]</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-9749.342***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-12277.122***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-44.666)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-84.535)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">transporta</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-23895.013***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-17.986)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">poverty_pe</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-7491.906***</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-40.361)</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">EHD_percen</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-2575.047***</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64"></span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">(-46.591)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">Num.Obs.</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">21200</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">21200</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">21200</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">R2</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">0.510</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">0.655</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">0.662</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">R2 Adj.</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">0.510</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">0.655</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">0.661</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">AIC</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">588488.8</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">581042.0</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">580636.9</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">BIC</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">588640.0</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">581217.1</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">580804.1</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">Log.Lik.</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-294225.378</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-290498.985</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">-290297.438</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">F</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">1297.057</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">2012.817</span></p></td><td class="cl-6c77d11c"><p class="cl-6c77a688"><span class="cl-6c71fd64">2180.926</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6c77d11d"><p class="cl-6c77a688"><span class="cl-6c71fd64">RMSE</span></p></td><td class="cl-6c77d11d"><p class="cl-6c77a688"><span class="cl-6c71fd64">257716.91</span></p></td><td class="cl-6c77d11d"><p class="cl-6c77a688"><span class="cl-6c71fd64">216175.05</span></p></td><td class="cl-6c77d11d"><p class="cl-6c77a688"><span class="cl-6c71fd64">214129.63</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td colspan="4" class="cl-6c77d11d"><p class="cl-6c77a674"><span class="cl-6c71fd64">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</span></p></td></tr></tfoot></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>En regresjonstabell for de tre hedoniske modellene er gitt i <a href="#tbl-1" class="quarto-xref">Table&nbsp;1</a> . I modell 1, som kun inkluderer huskarakteristika og tidsdummier, er antall soverom negativt assosiert med boligprisene (-59,606.36), boliger med flere soverom har lavere priser. Antall bad har en positiv effekt (6,795.04), og større boareal øker prisen (315.57). Tomtestørrelse har en negativ effekt på -0.399, mens antall etasjer ikke har en signifikant innvirkning på prisene. T-verdiene for huskarakteristikaene er alle høye, noe som indikerer at disse er signifikante, mens antall etasjer ikke er signifikant (t-verdi er lav). Når det gjelder tidsdummier, viser resultatene at prisene varierer betydelig fra måned til måned, med noen måneder som har positive effekter på prisen, mens andre har en negativ effekt. Mai 2014 er referansemåneden, noe som betyr at alle de andre dummykoeffisientene i modellen viser prisforskjellen sammenlignet med mai 2014. Det er få av tidsdummiene som er signifikante, noe som gjelder for alle modellene.</p>
<p>Modell 2 som inkluderer distanse til CBD, transport og fattigdom, viser at boliger lengre unna sentrum har lavere priser (-9,749.34), mens dårligere transport og høyere fattigdom reduserer boligprisene (-23,895.01 og -7,491.91). T-verdiene for disse variablene er høye, noe som betyr at de har en signifikant innvirkning på boligprisene. Resultatene viser også at flere soverom (-49,195.38) reduserer prisen, mens flere bad (19,338.31) og større boareal (294.54) øker prisen. Større tomt (0.43) har også en positiv effekt, men med mindre innvirkning enn boareal. Flere etasjer (-22,766.37) ser ut til å redusere prisen. Alle koeffisientene for huskrakteristika har høy T-verdi. Tidsdummiene for 2015 viser igjen variasjon i boligprisene.</p>
<p>Modell 3 som inkluderer EHD-indeksen, viser at dårligere miljøforhold er assosiert med lavere boligpriser (-2,575.05). T-verdien for miljøindeksen er relativt høy, som indikerer at den er signifikant. De andre koeffisientene for huskarakteristika, som soverom, bad, boareal, og tomtestørrelse, er stort sett konsistente med de tidligere modellene, og har signifikante t-verdier.. Tidsdummiene i modell 3 viser også variasjon i boligprisene gjennom året, med noen måneder som har en positiv effekt på prisene, mens andre måneder har en negativ effekt på prisene.</p>
</section>
<section id="sammenligning-av-de-tre-modellene---hvilken-er-best" class="level2">
<h2 class="anchored" data-anchor-id="sammenligning-av-de-tre-modellene---hvilken-er-best">4.2 Sammenligning av de tre modellene - Hvilken er best?</h2>
<p><strong>R² og justert R²</strong></p>
<p>Modell 1 har den laveste R² og justert R², noe som tyder på at den forklarer minst av variasjonen i dataene. Modell 2 har en betydelig høyere R²og justert R² enn modell 1, noe som indikerer en bedre forklaringsevne. Modell 3 har den høyeste R² og justert R², som tyder på at den gir den beste forklaringen av boligprisene blant de tre modellene. Basert på R² og justert R² ser Modell 3 ut til å være den mest pålitelige av de tre, da den forklarer mest av variasjonen i boligprisene.</p>
<p><strong>AIC og BIC</strong></p>
<p>Model 1 har en AIC-verdi på 588488.8, mens model 2 har en AIC-verdi på 581042.0. Model 3 har den laveste AIC-verdien på 580636.9. Lavere AIC-verdi betyr at model 3 er å foretrekke over model 1 og model 2, siden den gir en bedre balanse mellom tilpasning og kompleksitet.</p>
<p>Model1 har en BIC-verdi på 588640.0, model 2 har en BIC-verdi på 581217.1, og model 3 har den laveste BIC-verdien på 580804.1.BIC-verdi følger samme prinsipp som AIC: lavere verdier er bedre. Også her har model 3 den laveste verdien, noe som indikerer at model 3 er den beste modellen av de tre når man også tar hensyn til modellens kompleksitet.</p>
<p><strong>Log-likelihood</strong></p>
<p>Log-likelihood er en måling av modellens sannsynlighet; høyere log-likelihood er bedre. Modell 3 har høyest log-likelihood med en verdi på -290297.438, som betyr at den gir best tilpasning til dataene sammenlignet med de andre modellene.</p>
<p><strong>F-verdi</strong></p>
<p>F-verdien indikerer hvor godt modellen samlet sett forklarer variasjonen i boligprisene. Fra tabellen ser vi at F-verdien øker fra modell 1 (1297.057) til modell 3 (2180.926), noe som tyder på at den siste modellen har er best. Denne økningen i F-verdien fra modell 1 til modell 3 indikerer at når vi inkluderer flere variabler forbedres modellens forklaringskraft betraktelig.</p>
<p><strong>RMSE</strong></p>
<p>RMSE (Root Mean Squared Error) viser gjennomsnittlig avvik mellom de faktiske og de predikerte boligprisene. Den faller fra modell 1 (257716.91) til modell 3 (214129.63), noe som betyr at Modell 3 gir de mest presise prediksjonene og har lavest feilmargin.</p>
<p><strong>Konklusjon</strong></p>
<p>Modell 3 ser ut til å være den mest pålitelige og presise modellen. Modell 3 har den høyeste R² og justert R², noe som indikerer at den forklarer mest av variasjonen i prisene. I tillegg har modell 3 de laveste AIC- og BIC-verdiene, som viser at modellen gir en god balanse mellom kompleksitet og tilpasning. Med høyest log-likelihood og en betydelig forbedret F-verdi, er modell 3 også bedre tilpasset dataene enn de andre modellene. Modell 3 har også den laveste RMSE-verdien, noe som tyder på at den gir de mest presise prediksjonene med minst avvik fra de faktiske boligprisene.</p>
</section>
<section id="residualanalyse" class="level2">
<h2 class="anchored" data-anchor-id="residualanalyse">4.3 Residualanalyse</h2>
<p>Videre utføres en residual- og diagostikkanalyse for å vurdere modellens egenskaper ytterligere. Vi skal se nærmere på de fire plottene; “Residuals vs Fitted”, “Q-Q Residuals”, “Scale-Location” og “Residuals vs Leverage” for de tre hedoniske modellene. <a href="#fig-3" class="quarto-xref">Figure&nbsp;3</a> presenterer de fire plottene for modell 1, mens <a href="#fig-4" class="quarto-xref">Figure&nbsp;4</a> viser de samme plottene for modell 2, og til slutt gir <a href="#fig-5" class="quarto-xref">Figure&nbsp;5</a> en presentasjon av de fire plottene for modell 3.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-3" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="arbeidskrav_files/figure-html/fig-3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Residual- og diagnostikkplott for Modell 1
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-4" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="arbeidskrav_files/figure-html/fig-4-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Residual- og diagnostikkplott for Modell 2
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-5" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="arbeidskrav_files/figure-html/fig-5-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Residual- og diagnostikkplott for Modell 3
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Residuals vs Fitted</strong></p>
<p>Dette plottet viser forholdet mellom residualene og de tilpassede verdiene. Et godt tilpasset lineært forhold skal vise en tilfeldig fordeling av punktene rundt null-linjen, uten tydelige mønstre. I alle modellene ser vi litt avvik fra en helt jevn fordeling. For noen av modellene, spesielt modell 1, kan vi se noen mønstre som tyder på at modellen ikke helt fanger opp alle aspekter av dataene. Modell 3 ser ut til å ha en jevnere fordeling enn de andre modellene, noe som indikerer at denne modellen kan ha en bedre tilpasning. Samtidig ser vi tegn på heteroskedastisitet i form av en svak spredning i residualene for alle modellene. Dette antyder at variansen i feilene ikke er konstant, noe som kan påvirke modellenes presisjon og innebærer at estimatene ikke er like pålitelige over hele verdiskalaen.</p>
<p><strong>Q-Q Residuals</strong></p>
<p>Q-Q-plottet viser om residualene er normalfordelte ved å plotte de standardiserte residualene mot de teoretiske kvantilene for en normalfordeling. I alle modellene ser vi at noen punkter, spesielt i ytterkantene, avviker betydelig fra den teoretiske linjen. Dette indikerer at det er enkelte avvik eller “outliers” som ikke følger normalfordelingen. Modell 3 ser ut til å ha litt færre avvik enn de andre modellene, men det er fortsatt tegn på at noen residualer ikke er helt normalfordelte.</p>
<p><strong>Scale-Location</strong></p>
<p>Dette plottet viser kvadratroten av de standardiserte residualene mot de tilpassede verdiene. En jevn fordeling av punktene langs null-linjen indikerer homoskedastisitet . I alle modellene ser vi en svak trend der variansen øker med de tilpassede verdiene, noe som indikerer at det kan være heteroskedastisitet. Modell 3 ser igjen litt bedre ut enn modell 1 og modell 2, men heteroskedastisitet kan fortsatt være et problem noe som potensielt kan redusere modellenes robusthet og nøyaktighet i prediksjonene.</p>
<p><strong>Residuals vs Leverage</strong></p>
<p>Dette plottet viser hvilke observasjoner som har stor innflytelse på modellen og hvor store residualene er for disse observasjonene. Punkter som ligger langt fra de fleste dataene, og spesielt de som har høy leverage, kan være “influential points” som påvirker modellen betydelig. I alle modellene ser vi noen observasjoner med høy leverage, spesielt i ytterkantene. Cook’s distance-linjene hjelper oss å identifisere punkter med stor påvirkning. For eksempel ser vi noen observasjoner som kan påvirke modellens resultater betydelig. Modell 3 ser ut til å ha færre punkter med høy leverage enn de andre modellene, noe som kan indikere en bedre robusthet mot ekstreme observasjoner.</p>
<p><strong>Konklusjon</strong></p>
<p>Samlet sett gir modell 3 den beste tilpasningen blant de tre, men det er fortsatt noen utfordringer. Den har en jevnere fordeling i <em>Residuals vs Fitted</em>-plottet og færre punkter med høy leverage sammenlignet med de andre modellene, noe som indikerer bedre tilpasning. Men heteroskedastisitet og manglende normalitet i residualene utfordrer fortsatt modellens nøyaktighet og pålitelighet, noe som tyder på at det kan være rom for videre forbedring.</p>
</section>
</section>
<section id="simultan-test-på-tids-dummiene" class="level1">
<h1><strong>5.0 Simultan test på tids-dummiene</strong></h1>
<p>Videre skal vi bruke en simultan test på tids-dummiene i hver av de hedoniske modellene for å avgjøre om vi trenger de.</p>
<section id="model-1" class="level2">
<h2 class="anchored" data-anchor-id="model-1">5.1 Model 1</h2>
<p><a href="#fig-6" class="quarto-xref">Figure&nbsp;6</a> viser resultatene fra en simultantest på tids-dummiene i modell 1.</p>
<p><strong>F-verdi</strong>: 5.717</p>
<p><strong>p-verdi</strong>: 6.082e-10 (som er ekstremt lav, mindre enn 0.001)</p>
<p>For Model 1 indikerer den lave p-verdien (p &lt; 0.001) at vi kan avvise nullhypotesen om at alle tids-dummiene samlet er lik null. Dette betyr at tids-dummiene har en signifikant effekt på modellens forklaringskraft, og de bør inkluderes i modellen.</p>
<div class="cell">
<div id="fig-6" class="cell-output-display quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="tabwid"><style>.cl-74f5ac38{}.cl-74eb8870{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-74f002e2{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-74f002f6{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-74f026dc{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-74f026f0{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-74f026fa{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-74f02704{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-74f02705{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-74f0270e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-74f5ac38"><thead><tr style="overflow-wrap:break-word;"><th class="cl-74f026dc"><p class="cl-74f002e2"><span class="cl-74eb8870">Model Description</span></p></th><th class="cl-74f026f0"><p class="cl-74f002f6"><span class="cl-74eb8870">Res. Df</span></p></th><th class="cl-74f026f0"><p class="cl-74f002f6"><span class="cl-74eb8870">Df</span></p></th><th class="cl-74f026f0"><p class="cl-74f002f6"><span class="cl-74eb8870">F-Statistic</span></p></th><th class="cl-74f026f0"><p class="cl-74f002f6"><span class="cl-74eb8870">Pr..F.</span></p></th><th class="cl-74f026dc"><p class="cl-74f002e2"><span class="cl-74eb8870">Significance</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-74f026fa"><p class="cl-74f002e2"><span class="cl-74eb8870">Restricted Model</span></p></td><td class="cl-74f02704"><p class="cl-74f002f6"><span class="cl-74eb8870">21,194</span></p></td><td class="cl-74f02704"><p class="cl-74f002f6"><span class="cl-74eb8870"></span></p></td><td class="cl-74f02704"><p class="cl-74f002f6"><span class="cl-74eb8870"></span></p></td><td class="cl-74f02704"><p class="cl-74f002f6"><span class="cl-74eb8870"></span></p></td><td class="cl-74f026fa"><p class="cl-74f002e2"><span class="cl-74eb8870"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-74f02705"><p class="cl-74f002e2"><span class="cl-74eb8870">Model 1</span></p></td><td class="cl-74f0270e"><p class="cl-74f002f6"><span class="cl-74eb8870">21,182</span></p></td><td class="cl-74f0270e"><p class="cl-74f002f6"><span class="cl-74eb8870">12</span></p></td><td class="cl-74f0270e"><p class="cl-74f002f6"><span class="cl-74eb8870">5.717</span></p></td><td class="cl-74f0270e"><p class="cl-74f002f6"><span class="cl-74eb8870">0.0000000006082</span></p></td><td class="cl-74f02705"><p class="cl-74f002e2"><span class="cl-74eb8870">***</span></p></td></tr></tbody></table></div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Simultan test på tids-dummiene for Modell 1
</figcaption>
</figure>
</div>
</div>
</section>
<section id="modell-2" class="level2">
<h2 class="anchored" data-anchor-id="modell-2">5.2 Modell 2</h2>
<p><a href="#fig-7" class="quarto-xref">Figure&nbsp;7</a> viser resultatene fra en simultantest på tids-dummiene i modell 2.</p>
<p><strong>F-verdi</strong>: 8.2016</p>
<p><strong>p-verdi</strong>: 1.245e-15 (også ekstremt lav)</p>
<p>I Model 2 er p-verdien også svært lav, noe som igjen betyr at vi kan avvise nullhypotesen. Tids-dummiene har en signifikant effekt på boligprisene i denne modellen og bør beholdes.</p>
<div class="cell">
<div id="fig-7" class="cell-output-display quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="tabwid"><style>.cl-754bd630{}.cl-7541d644{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7545ec02{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7545ec16{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7546264a{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7546265e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-75462668{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-75462669{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-75462672{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7546267c{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-754bd630"><thead><tr style="overflow-wrap:break-word;"><th class="cl-7546264a"><p class="cl-7545ec02"><span class="cl-7541d644">Model Description</span></p></th><th class="cl-7546265e"><p class="cl-7545ec16"><span class="cl-7541d644">Res. Df</span></p></th><th class="cl-7546265e"><p class="cl-7545ec16"><span class="cl-7541d644">Df</span></p></th><th class="cl-7546265e"><p class="cl-7545ec16"><span class="cl-7541d644">F-Statistic</span></p></th><th class="cl-7546265e"><p class="cl-7545ec16"><span class="cl-7541d644">Pr..F.</span></p></th><th class="cl-7546264a"><p class="cl-7545ec02"><span class="cl-7541d644">Significance</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-75462668"><p class="cl-7545ec02"><span class="cl-7541d644">Restricted Model</span></p></td><td class="cl-75462669"><p class="cl-7545ec16"><span class="cl-7541d644">21,191</span></p></td><td class="cl-75462669"><p class="cl-7545ec16"><span class="cl-7541d644"></span></p></td><td class="cl-75462669"><p class="cl-7545ec16"><span class="cl-7541d644"></span></p></td><td class="cl-75462669"><p class="cl-7545ec16"><span class="cl-7541d644"></span></p></td><td class="cl-75462668"><p class="cl-7545ec02"><span class="cl-7541d644"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-75462672"><p class="cl-7545ec02"><span class="cl-7541d644">Model 2</span></p></td><td class="cl-7546267c"><p class="cl-7545ec16"><span class="cl-7541d644">21,179</span></p></td><td class="cl-7546267c"><p class="cl-7545ec16"><span class="cl-7541d644">12</span></p></td><td class="cl-7546267c"><p class="cl-7545ec16"><span class="cl-7541d644">8.2016</span></p></td><td class="cl-7546267c"><p class="cl-7545ec16"><span class="cl-7541d644">0.000000000000001245</span></p></td><td class="cl-75462672"><p class="cl-7545ec02"><span class="cl-7541d644">***</span></p></td></tr></tbody></table></div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Simultan test på tids-dummiene for Modell 2
</figcaption>
</figure>
</div>
</div>
</section>
<section id="modell-3" class="level2">
<h2 class="anchored" data-anchor-id="modell-3">5.3 Modell 3</h2>
<p><a href="#fig-8" class="quarto-xref">Figure&nbsp;8</a> viser resultatene fra en simultantest på tids-dummiene i modell 3.</p>
<p><strong>F-verdi</strong>: 9.1943</p>
<p><strong>p-verdi</strong>: &lt; 2.2e-16 (enda lavere enn de to foregående modellene)</p>
<p>For Model 3 er resultatet det samme: den lave p-verdien indikerer at tids-dummiene er signifikante for å forklare variasjonen i boligprisene, og derfor bør tids-dummiene inkluderes i modellen.</p>
<div class="cell">
<div id="fig-8" class="cell-output-display quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="tabwid"><style>.cl-75956066{}.cl-758b2150{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-758f23c2{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-758f23d6{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-758f5842{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-758f5856{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-758f5857{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-758f5860{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-758f586a{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-758f5874{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-75956066"><thead><tr style="overflow-wrap:break-word;"><th class="cl-758f5842"><p class="cl-758f23c2"><span class="cl-758b2150">Model Description</span></p></th><th class="cl-758f5856"><p class="cl-758f23d6"><span class="cl-758b2150">Res. Df</span></p></th><th class="cl-758f5856"><p class="cl-758f23d6"><span class="cl-758b2150">Df</span></p></th><th class="cl-758f5856"><p class="cl-758f23d6"><span class="cl-758b2150">F-Statistic</span></p></th><th class="cl-758f5856"><p class="cl-758f23d6"><span class="cl-758b2150">Pr..F.</span></p></th><th class="cl-758f5842"><p class="cl-758f23c2"><span class="cl-758b2150">Significance</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-758f5857"><p class="cl-758f23c2"><span class="cl-758b2150">Restricted Model</span></p></td><td class="cl-758f5860"><p class="cl-758f23d6"><span class="cl-758b2150">21,192</span></p></td><td class="cl-758f5860"><p class="cl-758f23d6"><span class="cl-758b2150"></span></p></td><td class="cl-758f5860"><p class="cl-758f23d6"><span class="cl-758b2150"></span></p></td><td class="cl-758f5860"><p class="cl-758f23d6"><span class="cl-758b2150"></span></p></td><td class="cl-758f5857"><p class="cl-758f23c2"><span class="cl-758b2150"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-758f586a"><p class="cl-758f23c2"><span class="cl-758b2150">Model 3</span></p></td><td class="cl-758f5874"><p class="cl-758f23d6"><span class="cl-758b2150">21,180</span></p></td><td class="cl-758f5874"><p class="cl-758f23d6"><span class="cl-758b2150">12</span></p></td><td class="cl-758f5874"><p class="cl-758f23d6"><span class="cl-758b2150">9.1943</span></p></td><td class="cl-758f5874"><p class="cl-758f23d6"><span class="cl-758b2150">0.00000000000000022</span></p></td><td class="cl-758f586a"><p class="cl-758f23c2"><span class="cl-758b2150">***</span></p></td></tr></tbody></table></div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Simultan test på tids-dummiene for Modell 3
</figcaption>
</figure>
</div>
</div>
<p>For alle tre modellene er p-verdiene ekstremt lave, langt under 0.05, noe som indikerer at tids-dummiene samlet sett har en signifikant effekt på modellene. Med andre ord, tids-dummiene bør inkluderes i alle modellene fordi de bidrar til å forklare variasjonen i boligprisene over tid. Dette betyr at tidsvariasjon er viktig for å modellere boligprisene i dette datasettet.</p>
</section>
</section>
<section id="spatial-regressions" class="level1">
<h1><strong>6.0 Spatial Regressions</strong></h1>
<p>Videre skal vi utføre «spatial regressions» på et subset på ca. 2000 observasjoner fra det totale datasettet. Vi skal finne ut hvilken romlig regresjonsmodell som best fanger opp de romlige effektene. Vi skal se på valg av modell ved hjelp av metodene til både <span class="citation" data-cites="anselin1988">Anselin (<a href="#ref-anselin1988" role="doc-biblioref">1988</a>)</span> og <span class="citation" data-cites="lesage">LeSage (<a href="#ref-lesage" role="doc-biblioref">n.d.</a>)</span></p>
<section id="ols-modell-og-spatial-effects" class="level2">
<h2 class="anchored" data-anchor-id="ols-modell-og-spatial-effects">6.1 OLS-modell og “Spatial effects”</h2>
<p>Før vi går over på romlige regresjonsmodeller skal vi presentere modellen vi ønsker å bruke. Vi kjører den som en OLS-modell og ser nærmere på residualene for å avgjøre om vi har uforklarte “spatial effects” i residualene. Følgende modell er spesifisert:</p>
<p><span class="math inline">\(P_i = \beta_0 + \beta_1 \cdot \text{bedrooms}_i + \beta_2 \cdot \text{bathrooms}_i + \beta_3 \cdot \text{sqft\_living}_i + \beta_4 \cdot \text{sqft\_lot}_i + \beta_5 \cdot \text{floors}_i + \beta_6 \cdot \text{andel\_hvit\_alene}_i + \beta_7 \cdot \text{andel\_svart\_alene}_i + \beta_8 \cdot \text{andel\_asiatisk\_alene}_i + \beta_9 \cdot \text{andel\_andre\_alene}_i + \beta_{10} \cdot \text{andel\_blandet}_i + \epsilon_i\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Global Moran I for regression residuals

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
weights: lw3

Moran I statistic standard deviate = 25.384, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Observed Moran I      Expectation         Variance 
    0.4421560581    -0.0025985312     0.0003069769 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Global Moran I for regression residuals

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
weights: lw10

Moran I statistic standard deviate = 40.616, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Observed Moran I      Expectation         Variance 
    0.3904096022    -0.0020984966     0.0000933904 </code></pre>
</div>
</div>
<p>Resultatene fra Moran’s I-testen indikerer at det er en signifikant romlig autokorrelasjon i residualene fra regresjonsmodellen. For Moran’s I med 3 naboer fikk vi en observert Moran I-verdi på 0.442 med ett standardavvik på 25.384 og en p-verdi på mindre enn 2.2e-16. For Moran’s I med 10 naboer var den observerte Moran I-verdien 0.390 med ett standardavvik på 40.616 og en p-verdi på mindre enn 2.2e-16. Begge testene gir svært lave p-verdier, noe som betyr at vi kan forkaste nullhypotesen om ingen romlig autokorrelasjon i residualene.</p>
<p>Moran’s I-verdiene for både 3 og 10 naboer er positive og signifikante, noe som indikerer at residualene fra modellen er spatialt korrelerte. Dette betyr at det er spatial avhengighet som modellen ikke har klart å fange opp. Den romlige korrelasjonen er noe sterkere for nærmeste 3 naboer sammenlignet med nærmeste 10 naboer, noe som tyder på at den romlige korrelasjonen kan være mer lokal i naturen.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-11" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="arbeidskrav_files/figure-html/fig-11-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Morans plott for OLS residualer k = 3
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-12" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="arbeidskrav_files/figure-html/fig-12-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Moran`s plott for OLS residualer k = 10
</figcaption>
</figure>
</div>
</div>
</div>
<p>Moran-plottene for OLS-residualene gir en visuell representasjon av romlig autokorrelasjon i modellens residualer. Moran-plottene viser forholdet mellom residualene (x-aksen) og de spatialt forsinkede residualene (y-aksen), og gjør det mulig å vurdere om det finnes systematiske romlige mønstre. Moran-plottet for 3 nærmeste naboer indikerer en positiv romlig autokorrelasjon. Vi kan se at flere datapunkter ligger i kvadrantene som representerer lav-lav og høy-høy, noe som betyr at områder med høye restverdier tenderer til å være nær andre områder med høye restverdier, og tilsvarende for lave verdier. Den stigende trenden i plottet bekrefter også at det er en klar sammenheng mellom restverdiene og deres spatialt forsinkede motparter. Moran-plottet for 10 nærmeste naboer har en lignende trend som for 3 nærmeste naboer, men sammenhengen ser noe svakere ut. Dette skyldes sannsynligvis at k = 10 inkluderer flere naboer, noe som utjevner den lokale romlige korrelasjonen. Den stigende linjen indikerer fortsatt at det er en positiv romlig autokorrelasjon, men denne effekten blir noe mindre markant når flere naboer inkluderes.</p>
<p>Funnene fra Morans I testene og plottene indikerer at OLS-modellen ikke er tilstrekkelig i å fange opp alle de romlige forholdene som påvirker boligprisene. For å håndtere denne romlige autokorrelasjonen bør det vurderes å bruke romlige regresjonsmodeller, noe vi skal ser nærmere på videre i oppgaven.</p>
</section>
<section id="anselin" class="level2">
<h2 class="anchored" data-anchor-id="anselin">6.2 Anselin</h2>
<p>Her blir <span class="citation" data-cites="anselin1988">Anselin (<a href="#ref-anselin1988" role="doc-biblioref">1988</a>)</span> sin teknikk med Lagrange multiplikator test brukt og videre diskuteres det hvilken modell (SAR, SEM eller lm (OLS)) som synes å være den beste. Vi undersøker både for 3 og 10 nærmeste naboer.</p>
<section id="langrange-multiplikator-test-for-3-nærmeste-naboer-k-3" class="level3">
<h3 class="anchored" data-anchor-id="langrange-multiplikator-test-for-3-nærmeste-naboer-k-3">6.2.1 Langrange multiplikator test for 3 nærmeste naboer (k = 3)</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lagrange Multiplikator-tester med k=3"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

RSerr = 632.79, df = 1, p-value &lt; 2.2e-16


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

RSlag = 597.42, df = 1, p-value &lt; 2.2e-16


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

adjRSerr = 99.077, df = 1, p-value &lt; 2.2e-16


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

adjRSlag = 63.709, df = 1, p-value = 1.443e-15


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

SARMA = 696.5, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>OLS-modellen</strong>: Basert på de svært signifikante p-verdiene fra alle testene, kan vi konkludere med at OLS-modellen ikke klarer å håndtere romlige avhengigheter i dataene på en tilfredsstillende måte. Residualene fra OLS-modellen viser klare tegn på romlig autokorrelasjon, og dette betyr at en modell som tar hensyn til disse effektene vil være mer hensiktsmessig.</p>
<p><strong>Spatial Error Model (SEM)</strong>: Teststatistikken for RSerr og adjRSerr er høy, og begge testene er svært signifikante. Dette tyder på at romlig avhengighet primært eksisterer i errorleddene, noe som gjør SEM til en god kandidat for videre modellering.</p>
<p><strong>Spatial Lag Model (SAR)</strong>: Teststatistikken for RSlag og adjRSlag er også høy og signifikant, noe som indikerer at romlig avhengighet også finnes i selve avhengighetsforholdene i modellen. SAR-modellen vil derfor kunne være en god modell for å fange opp disse effektene.</p>
<p>Gitt resultatene fra Lagrange multiplikator-testene, synes både SEM og SAR å være aktuelle modeller for å håndtere de romlige avhengighetene. Valget mellom de to modellene avhenger av hvilken type romlig avhengighet som antas å være mest relevant:</p>
<ul>
<li>Hvis romlig avhengighet antas å påvirke feilleddene, er SEM den beste modellen.</li>
<li>Hvis romlig avhengighet antas å være i den avhengige variabelens forhold til de forklarende variablene, vil SAR være mer hensiktsmessig.</li>
</ul>
</section>
<section id="langrange-multiplikator-test-for-10-nærmeste-naboer-k-10" class="level3">
<h3 class="anchored" data-anchor-id="langrange-multiplikator-test-for-10-nærmeste-naboer-k-10">6.2.2 Langrange multiplikator test for 10 nærmeste naboer (k = 10)</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lagrange Multiplikator-tester med k=10"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

RSerr = 1593.2, df = 1, p-value &lt; 2.2e-16


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

RSlag = 1104.5, df = 1, p-value &lt; 2.2e-16


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

adjRSerr = 568.87, df = 1, p-value &lt; 2.2e-16


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

adjRSlag = 80.235, df = 1, p-value &lt; 2.2e-16


    Rao's score (a.k.a Lagrange multiplier) diagnostics for spatial
    dependence

data:  
model: lm(formula = price ~ bedrooms + bathrooms + sqft_living +
sqft_lot + floors + andel_hvit_alene + andel_svart_alene +
andel_asiatisk_alene + andel_andre_alene + andel_blandet, data =
data_with_area_vars)
test weights: listw

SARMA = 1673.4, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>OLS-modellen</strong>: Gitt de svært signifikante p-verdiene fra alle testene, ser vi at OLS-modellen ikke klarer å håndtere romlige avhengigheter i dataene. Residualene fra OLS-modellen viser tydelige tegn på romlig autokorrelasjon, noe som gjør at en annen modell er nødvendig.</p>
<p><strong>Spatial Error Model (SEM)</strong>: RSerr og adjRSerr har de høyeste teststatistikkene og svært signifikante p-verdier. Dette tyder på at den romlige avhengigheten hovedsakelig ligger i errorleddene, og at en SEM derfor vil være en passende modell for videre analyse.</p>
<p><strong>Spatial Lag Model (SAR)</strong>: RSlag og adjRSlag viser også signifikante resultater, men teststatistikkene er lavere sammenlignet med SEM. Dette kan indikere at selv om det er en romlig avhengighet i den avhengige variabelen, er denne effekten ikke like sterk som den romlige avhengigheten i errorleddene. SAR-modellen kan være et alternativ, men SEM virker å være mer relevant basert på testresultatene.</p>
<p>Basert på resultatene fra Lagrange multiplikator-testene med k = 10, virker Spatial Error Model (SEM) å være det beste alternativet for å håndtere de romlige avhengighetene i dataene. Teststatistikken for RSerr og adjRSerr er høyere enn for RSlag og adjRSlag, noe som tyder på at romlig avhengighet primært er til stede i errorleddene. Dette betyr at en SEM-modell kan gi en bedre modelltilpasning enn SAR.</p>
</section>
<section id="konklusjon" class="level3">
<h3 class="anchored" data-anchor-id="konklusjon">6.2.3 Konklusjon</h3>
<p>Samlet sett peker Lagrange Multiplikator-testene mot at en Spatial Error Model (SEM) vil være den mest passende modellen for dette datasettet. En SEM-modell vil kunne håndtere den observerte spatial avhengigheten ved å modellere romlige effekter i feilkomponenten, noe som sannsynligvis gir en bedre forståelse og kontroll av romlige mønstre i boligprisene enn en SAR- eller OLS-modell ville ha gjort.</p>
</section>
<section id="sar" class="level3">
<h3 class="anchored" data-anchor-id="sar">6.2.4 SAR</h3>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lagsarlm(formula = price ~ bedrooms + bathrooms + sqft_living + :
Aliased variables found: andel_blandet</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lagsarlm(formula = price ~ bedrooms + bathrooms + sqft_living + : inversion of asymptotic covariance matrix failed for tol.solve = 2.22044604925031e-16 
  reciprocal condition number = 3.13248e-23 - using numerical Hessian.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in sqrt(diag(fdHess)[-1]): NaNs produced</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lagsarlm(formula = price ~ bedrooms + bathrooms + sqft_living + :
Aliased variables found: andel_blandet</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lagsarlm(formula = price ~ bedrooms + bathrooms + sqft_living + : inversion of asymptotic covariance matrix failed for tol.solve = 2.22044604925031e-16 
  reciprocal condition number = 3.61831e-23 - using numerical Hessian.</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:lagsarlm(formula = price ~ bedrooms + bathrooms + sqft_living + 
    sqft_lot + floors + andel_hvit_alene + andel_svart_alene + 
    andel_asiatisk_alene + andel_andre_alene + andel_blandet, 
    data = data_with_area_vars, listw = lw3, method = "eigen")

Residuals:
    Min      1Q  Median      3Q     Max 
-602692  -99358  -12857   72370 2671722 

Type: lag 
Coefficients: (numerical Hessian approximate standard errors) 
    (1 not defined because of singularities)
                        Estimate  Std. Error z value  Pr(&gt;|z|)
(Intercept)          -1.1098e+05  4.4342e+04 -2.5028   0.01232
bedrooms             -3.9716e+04  5.9416e+03 -6.6844 2.319e-11
bathrooms            -1.0549e+03         NaN     NaN       NaN
sqft_living           2.5769e+02  7.1535e+00 36.0229 &lt; 2.2e-16
sqft_lot             -2.7413e-01  1.0658e-01 -2.5720   0.01011
floors               -3.4810e+03  8.4995e+03 -0.4096   0.68214
andel_hvit_alene      6.5033e+04  3.7072e+04  1.7542   0.07939
andel_svart_alene    -9.8055e+04  6.1252e+04 -1.6008   0.10941
andel_asiatisk_alene -1.1777e+04  2.3205e+04 -0.5075   0.61178
andel_andre_alene    -2.3186e+05  9.1751e+04 -2.5271   0.01150
andel_blandet                 NA          NA      NA        NA

Rho: 0.45218, LR test value: 562.54, p-value: &lt; 2.22e-16
Approximate (numerical Hessian) standard error: 0.01641
    z-value: 27.555, p-value: &lt; 2.22e-16
Wald statistic: 759.28, p-value: &lt; 2.22e-16

Log likelihood: -25755.67 for lag model
ML residual variance (sigma squared): 3.9418e+10, (sigma: 198540)
Number of observations: 1887 
Number of parameters estimated: 12 
AIC: 51535, (AIC for lm: 52096)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:lagsarlm(formula = price ~ bedrooms + bathrooms + sqft_living + 
    sqft_lot + floors + andel_hvit_alene + andel_svart_alene + 
    andel_asiatisk_alene + andel_andre_alene + andel_blandet, 
    data = data_with_area_vars, listw = lw10, method = "eigen")

Residuals:
      Min        1Q    Median        3Q       Max 
-584205.0  -99189.2   -8409.4   67562.2 2545145.9 

Type: lag 
Coefficients: (numerical Hessian approximate standard errors) 
    (1 not defined because of singularities)
                        Estimate  Std. Error z value  Pr(&gt;|z|)
(Intercept)          -2.5904e+04  4.3289e+04 -0.5984  0.549575
bedrooms             -4.1191e+04  5.6814e+03 -7.2501 4.166e-13
bathrooms             2.9762e+03  5.2865e+03  0.5630  0.573449
sqft_living           2.5850e+02  7.3361e+00 35.2366 &lt; 2.2e-16
sqft_lot             -1.9462e-01  1.0028e-01 -1.9407  0.052299
floors               -6.8018e+03  7.3255e+03 -0.9285  0.353144
andel_hvit_alene     -1.3273e+05  5.0803e+04 -2.6126  0.008986
andel_svart_alene    -9.7941e+04  7.9444e+04 -1.2328  0.217638
andel_asiatisk_alene -2.6371e+05  6.3263e+04 -4.1685 3.067e-05
andel_andre_alene    -2.3976e+05  9.1532e+04 -2.6194  0.008808
andel_blandet                 NA          NA      NA        NA

Rho: 0.62416, LR test value: 708.64, p-value: &lt; 2.22e-16
Approximate (numerical Hessian) standard error: 0.019804
    z-value: 31.516, p-value: &lt; 2.22e-16
Wald statistic: 993.28, p-value: &lt; 2.22e-16

Log likelihood: -25682.62 for lag model
ML residual variance (sigma squared): 3.7103e+10, (sigma: 192620)
Number of observations: 1887 
Number of parameters estimated: 12 
AIC: 51389, (AIC for lm: 52096)</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Impact measures (lag, exact):
                            Direct      Indirect         Total
bedrooms             -4.257141e+04 -2.992584e+04 -7.249726e+04
bathrooms            -1.130777e+03 -7.948872e+02 -1.925665e+03
sqft_living           2.762187e+02  1.941697e+02  4.703883e+02
sqft_lot             -2.938421e-01 -2.065582e-01 -5.004002e-01
floors               -3.731296e+03 -2.622938e+03 -6.354235e+03
andel_hvit_alene      6.970877e+04  4.900222e+04  1.187110e+05
andel_svart_alene    -1.051056e+05 -7.388463e+04 -1.789902e+05
andel_asiatisk_alene -1.262395e+04 -8.874089e+03 -2.149804e+04
andel_andre_alene    -2.485331e+05 -1.747079e+05 -4.232410e+05</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Impact measures (lag, exact):
                            Direct      Indirect         Total
bedrooms             -4.362077e+04 -6.597474e+04 -1.095955e+05
bathrooms             3.151766e+03  4.766924e+03  7.918690e+03
sqft_living           2.737506e+02  4.140373e+02  6.877879e+02
sqft_lot             -2.060985e-01 -3.117161e-01 -5.178146e-01
floors               -7.203010e+03 -1.089428e+04 -1.809729e+04
andel_hvit_alene     -1.405558e+05 -2.125853e+05 -3.531411e+05
andel_svart_alene    -1.037191e+05 -1.568712e+05 -2.605903e+05
andel_asiatisk_alene -2.792646e+05 -4.223770e+05 -7.016416e+05
andel_andre_alene    -2.539032e+05 -3.840188e+05 -6.379220e+05</code></pre>
</div>
</div>
<p>Ved å bruke impacts()-funksjonen på SAR-modellen kan vi få nøyaktige tall for både direkte, indirekte og totale effekter, som gir en mer detaljert økonomisk tolkning av hvordan uklie atributter påvirker boligprisene i et romlig perspektiv.</p>
</section>
</section>
<section id="lesage" class="level2">
<h2 class="anchored" data-anchor-id="lesage">6.3 LeSage</h2>
<p>Vi skal nå bruke teknikken med nestede modeller anbefalt av <span class="citation" data-cites="lesage">LeSage (<a href="#ref-lesage" role="doc-biblioref">n.d.</a>)</span>, før vi tester de nestede modellne ved hjelp av en <em>likelihood ratio test</em> for å finne ut hvilken modell som synes å være den beste.</p>
<section id="lokalt-eller-globalt-fenomen" class="level3">
<h3 class="anchored" data-anchor-id="lokalt-eller-globalt-fenomen">6.3.1 Lokalt eller globalt fenomen?</h3>
<p>Vi har en høyere Moran`s I verdi for 3 nærmeste naboer (k=3) enn for 10 nærmeste naboer (k =10), noe som tyder på at den romlige autokorrelasjonen er sterkere når man ser på de nærmeste naboene og svekkes når man inkluderer flere naboer. Dette er et tegn på at fenomenet vi studerer kan være mer lokalt i naturen. Dette antyder at eventuelle romlige avhengigheter eller spillover-effekter påvirker områder i umiddelbar nærhet sterkere enn de mer fjerntliggende. I følge <span class="citation" data-cites="lesage">LeSage (<a href="#ref-lesage" role="doc-biblioref">n.d.</a>)</span> er globale spillover sjeldnere enn lokale spillovers i anvendte modeller innen regional vitenskap, og vi kan derfor si at de fleste romlige spillovers er lokale. Han mener også at bruk av modeller med ulike nivåer av romlig kompleksitet, som SDEM, SLX, og SEM, er fordelaktig når vi studerer et lokalt fenomen. Disse modellene er nestede, noe som betyr at de kan beskrives som spesialtilfeller (SLX og SEM) av en mer generell modellstruktur (SDEM).</p>
</section>
<section id="sdem" class="level3">
<h3 class="anchored" data-anchor-id="sdem">6.3.2 SDEM</h3>
<p>En Spatial Durbin Error Model (SDEM) er en romlig regresjonsmodell som tar hensyn til både direkte og indirekte (spillover) effekter i dataene. Den generelle formen for SDEM er:</p>
<p><span class="math inline">\(y = \rho W y + X \beta + \theta W X + \epsilon\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:errorsarlm(formula = model_ols, data = data_with_area_vars, listw = lw3, 
    Durbin = TRUE)

Residuals:
    Min      1Q  Median      3Q     Max 
-628718  -92774   -8054   65279 2609177 

Type: error 
Coefficients: (asymptotic standard errors) 
    (2 not defined because of singularities)
                            Estimate  Std. Error z value  Pr(&gt;|z|)
(Intercept)              -1.6796e+05  3.6627e+05 -0.4586  0.646549
bedrooms                 -4.5825e+04  6.3953e+03 -7.1653 7.760e-13
bathrooms                -2.3926e+03  1.0410e+04 -0.2298  0.818224
sqft_living               2.8357e+02  8.7668e+00 32.3456 &lt; 2.2e-16
sqft_lot                  1.5712e-02  1.0892e-01  0.1442  0.885304
floors                   -1.3412e+04  1.0521e+04 -1.2747  0.202408
andel_hvit_alene          1.3355e+05  2.4288e+05  0.5499  0.582413
andel_svart_alene        -8.3100e+04  2.8742e+05 -0.2891  0.772489
andel_asiatisk_alene      1.6148e+05  2.5609e+05  0.6306  0.528318
andel_andre_alene         1.2948e+05  2.8067e+05  0.4613  0.644567
andel_blandet                     NA          NA      NA        NA
lag.bedrooms             -3.8345e+04  1.2925e+04 -2.9668  0.003009
lag.bathrooms            -1.7204e+04  2.2058e+04 -0.7800  0.435414
lag.sqft_living           9.4158e+01  1.7986e+01  5.2350 1.650e-07
lag.sqft_lot             -1.0153e+00  2.4267e-01 -4.1839 2.866e-05
lag.floors                5.1975e+03  2.1570e+04  0.2410  0.809588
lag.andel_hvit_alene      2.4216e+05  3.6613e+05  0.6614  0.508367
lag.andel_svart_alene    -4.2911e+04  4.1989e+05 -0.1022  0.918602
lag.andel_asiatisk_alene  2.0921e+05  3.7638e+05  0.5559  0.578311
lag.andel_andre_alene    -6.1400e+05  4.2433e+05 -1.4470  0.147894
lag.andel_blandet                 NA          NA      NA        NA

Lambda: 0.5404, LR test value: 519.53, p-value: &lt; 2.22e-16
Approximate (numerical Hessian) standard error: 0.019802
    z-value: 27.289, p-value: &lt; 2.22e-16
Wald statistic: 744.71, p-value: &lt; 2.22e-16

Log likelihood: -25696.93 for error model
ML residual variance (sigma squared): 3.5849e+10, (sigma: 189340)
Number of observations: 1887 
Number of parameters estimated: 21 
AIC: 51436, (AIC for lm: 51953)</code></pre>
</div>
</div>
</section>
<section id="sem" class="level3">
<h3 class="anchored" data-anchor-id="sem">6.3.3 SEM</h3>
<p>En Spatial Error Model (SEM) er en romlig regresjonsmodell som fanger opp romlige autokorrelasjoner i feilleddet, i stedet for å inkorporere romlige effekter direkte i de uavhengige variablene. Den generelle formen for SEM er:</p>
<p><span class="math inline">\(y = X \beta + \epsilon\)</span> <span class="math inline">\(\epsilon = \lambda W \epsilon + \nu\)</span></p>
</section>
<section id="slx" class="level3">
<h3 class="anchored" data-anchor-id="slx">6.3.4 SLX</h3>
<p>En Spatial Lag of X (SLX)-modell er en romlig regresjonsmodell som tar hensyn til romlige spillover-effekter direkte i de uavhengige variablene. I motsetning til Spatial Error Model (SEM), som fanger opp romlig autokorrelasjon i feilleddet, inkorporerer SLX-modellen romlige effekter ved å inkludere romlige lag av de uavhengige variablene. Den generelle formelen for en SLX-modell er:</p>
<p><span class="math inline">\(y = X \beta + \rho W y + \epsilon\)</span></p>
</section>
<section id="testing-og-sammenligning-av-de-ulike-modellene" class="level3">
<h3 class="anchored" data-anchor-id="testing-og-sammenligning-av-de-ulike-modellene">6.3.6 Testing og sammenligning av de ulike modellene</h3>
<p>Vi skal nå teste og sammenligne de ulike modellene for å avgjøre hvilken som er mest passende.Vi bruker en likelihood ratio test til å sammenligne to modeller for å vurdere om den mer komplekse modellen gir en signifikant forbedring i modelltilpasning. I dette tilfellet har alle de romlige modellene (SEM, SDEM og SLX) signifikant lavere AIC og høyere log-likelihood enn OLS-modellen, noe som indikerer at de passer bedre til dataene.</p>
<p>SEM-modellen (AIC = 51 436) og SLX-modellen (AIC = 51 409) har begge lavere AIC-verdier enn SDEM-modellen (AIC = 51,502). AIC er et mål på modellens kvalitet, der lavere verdier indikerer en bedre modell som balanserer god tilpasning og modellkompleksitet.</p>
<p>SLX-modellen har den laveste AIC (51 409), noe som antyder at den gir den beste balansen mellom modelltilpasning og kompleksitet sammenlignet med de andre modellene. Log-likelihood er også høyest for SLX-modellen (-25,683.28), som bekrefter at den gir den beste tilpasningen til dataene.</p>
<p>Basert på AIC, log-likelihood, og likelihood ratio test ser SLX-modellen ut til å være den beste modellen for dette datasettet, siden den har den laveste AIC og høyeste log-likelihood. Selv om SEM-modellen også gir en betydelig forbedring i forhold til OLS og SDEM-modellen, indikerer AIC og log-likelihood at SLX-modellen gir den beste balansen mellom tilpasning og kompleksitet.</p>
</section>
</section>
<section id="fjerner-modellene-spatial-effects" class="level2">
<h2 class="anchored" data-anchor-id="fjerner-modellene-spatial-effects">6.4 Fjerner modellene “spatial effects”?</h2>
<p>Vi skal se nærmere på residualene fra de ulike modellene for å illustrere hvor godt hver modell fjerner «spatial effects» fra residualene. Vi ser kun på modellene for k=10 (10 nærmeste naboer).</p>
<p>For å evaluere hvor godt de ulike modellene (OLS, SEM, SAR, SDEM og SLX) håndterer spatial autokorrelasjon i boligprisdataene, har vi benyttet <strong>Moran’s I-plot</strong> på residualene fra hver modell med k=10 nærmeste naboer. Moran-plottene gir oss innsikt i hvorvidt modellene klarer å fjerne romlige effekter fra residualene og dermed oppnå en modelltilpasning som ikke er påvirket av spatial autokorrelasjon.</p>
<p><strong>OLS-modellen</strong>: Moran-plot for OLS-residualene viser tydelig spatial autokorrelasjon. Punktene i plottet er sterkt gruppert, spesielt rundt første og tredje kvadrant, som indikerer positiv romlig korrelasjon mellom residualene. Dette antyder at OLS-modellen ikke håndterer den romlige avhengigheten, noe som resulterer i at romlig strukturerte feil fortsatt er til stede. Den stigende linjen i plottet bekrefter at det er en romlig sammenheng mellom residualene, som indikerer behov for en modell som kan håndtere denne romlige avhengigheten.</p>
<p><strong>SEM-modellen (Spatial Error Model)</strong>:</p>
<p>Moran-plot for SEM-residualene viser en klar forbedring sammenlignet med OLS. Residualene er mer spredt, og det er mindre tydelig clustering i første og tredje kvadrant. Dette indikerer at SEM-modellen har klart å fange opp en stor del av den spatial autokorrelasjonen som var til stede i OLS-modellen.</p>
<p>Den fladere linjen i plottet viser at det er mindre romlig autokorrelasjon igjen i residualene, noe som tyder på at SEM-modellen har vært effektiv i å redusere romlig avhengighet i feilene.</p>
<p><strong>SDEM-modellen (Spatial Durbin Error Model)</strong>:</p>
<p>Moran-plot for SDEM-residualene viser et lignende mønster som SEM-modellen, med spredte residualer og mindre clustering. Dette bekrefter at også SDEM-modellen håndterer spatial autokorrelasjon godt, og at den fanger opp både direkte og indirekte romlige effekter.</p>
<p>Linjen i plottet er fortsatt noe stigende, men det er færre ekstreme verdier sammenlignet med OLS. SDEM-modellen ser ut til å være minst like effektiv som SEM i å håndtere romlige avhengigheter.</p>
<p><strong>SLX-modellen (Spatial Lag of X Model)</strong>:</p>
<p>Moran-plot for SLX-residualene viser at modellen klarer å redusere noe av den spatial autokorrelasjonen, men ikke i like stor grad som SEM eller SDEM. Det er fortsatt en viss clustering synlig, spesielt i første og tredje kvadrant, noe som tyder på at SLX-modellen ikke fullt ut håndterer romlig avhengighet i dataene. Sammenlignet med OLS er SLX en forbedring, men den flate linjen er ikke like tydelig som i SEM- eller SDEM-plottene. Dette indikerer at SLX-modellen er mindre effektiv når det gjelder å fjerne spatial autokorrelasjon i residualene.</p>
<p>Konklusjonen er at <strong>SEM og SDEM-modellene</strong> fjerner spatial autokorrelasjon best, med SEM som en lett overlegen modell, mens <strong>OLS</strong> sliter mest med å håndtere de romlige effektene. <strong>SLX-modellen</strong> klarer å redusere noe av den spatial avhengigheten, men ikke i like stor grad som SEM og SDEM.</p>
</section>
</section>
<section id="diskusjon-av-resultatene" class="level1">
<h1><strong>7.0 Diskusjon av resultatene</strong></h1>
<p>For denne diskusjonen vil vi fokusere på den hedoniske boligprismodellen, som er en metode for å estimere implisitte priser på boligens egenskaper, slik som størrelse, beliggenhet og sosioøkonomiske faktorer. Hver modell (OLS, SEM, SAR, SLX og SDEM) har blitt brukt for å undersøke hvordan disse egenskapene påvirker boligprisene, og gir oss innsikt i ulike aspekter av romlige avhengigheter.</p>
<p><strong>Økonomisk tolkning av den hedoniske boligprismodellen:</strong></p>
<p>Den hedoniske modellen antar at boligens pris er et resultat av dens unike egenskaper. Modellen dekomponerer prisen slik at vi kan se hvor mye av prisen som skyldes spesifikke attributter, som antall soverom, boligstørrelse, og lokalsamfunnets egenskaper. I en hedonisk boligprismodell betyr koeffisientene de implisitte prisene på de enkelte egenskapene. For eksempel vil en positiv koeffisient for “sqft_living” indikere at større boliger, alt annet likt, er forbundet med høyere priser.</p>
<p><strong>I OLS-modellen kan vi tolke to utvalgte koeffisienter med tanke på den hedoniske teorien:</strong></p>
<ol type="1">
<li><p>Koeffisient forbedrooms: Denne koeffisienten viser hvordan antall soverom påvirker boligprisen. Et negativt estimat indikerer at flere soverom faktisk kan redusere boligprisen når andre faktorer holdes konstant, noe som kan tolkes som at større boligareal (representert ved andre variabler som sqft_living) er viktigere enn antall soverom i å forklare prisøkning.</p></li>
<li><p>Koeffisient forsqft_living: Dette måler effekten av boareal på prisen og har en positiv koeffisient, som forventet. Økt boareal fører til en økning i pris, noe som er i tråd med den hedoniske teorien om at større boliger har høyere verdi på grunn av økt funksjonalitet og komfort.</p></li>
</ol>
<p><strong>I SDEM-modellen kan vi tolke to utvalgte koeffisienter med tanke på den hedoniske teorien:</strong></p>
<ol type="1">
<li>Koeffisient for sqft_living (boareal):</li>
</ol>
<ul>
<li>Direkte effekt: Den positive og signifikante direkte effekten (p-verdi &lt; 2.22e-16) indikerer at økt boareal innenfor enheten gir en økning i boligprisen. Dette stemmer godt med den hedoniske teorien, som sier at større boliger har høyere verdi.</li>
<li>Indirekte effekt: Den positive og signifikante indirekte effekten antyder også at boareal i naboområder påvirker boligprisen, noe som kan indikere en viss “nabolagseffekt” der større boliger i nærheten øker den generelle prisnivået i området.</li>
</ul>
<ol start="2" type="1">
<li>Koeffisient for bedrooms (antall soverom):</li>
</ol>
<ul>
<li>Direkte effekt: Den negative og signifikante direkte effekten (p-verdi 7.76e-13) antyder at et høyere antall soverom, når andre faktorer holdes konstant, kan redusere boligprisen. Dette kan tolkes som at boareal er viktigere enn antall rom i å bestemme verdien.</li>
<li>Indirekte effekt: Den indirekte effekten er også negativ og signifikant (p-verdi 0.003009), noe som betyr at flere soverom i nærområdet kan ha en negativ effekt på boligprisen, kanskje på grunn av preferanser for å unngå områder med mange små, trange boliger.</li>
</ul>
<p><strong>I SEM (Spatial Error Model) kan vi tolke to utvalgte koeffisienter med tanke på den hedoniske teorien:</strong></p>
<ol type="1">
<li>Koeffisient for sqft_living (boareal):</li>
</ol>
<ul>
<li>Den positive og svært signifikante koeffisienten (p-verdi &lt; 2.2e-16) indikerer at økt boareal er assosiert med høyere boligpris. Dette er i samsvar med den hedoniske teorien, som sier at større boareal gir økt verdi fordi det gir mer funksjonalitet og komfort.</li>
</ul>
<ol start="2" type="1">
<li>Koeffisient for bedrooms (antall soverom):</li>
</ol>
<ul>
<li>Den negative og signifikante koeffisienten (p-verdi 1.012e-10) antyder at flere soverom, når andre faktorer som boareal holdes konstant, kan redusere boligprisen. Dette kan indikere at boligkjøpere verdsetter boareal mer enn antall rom, som antyder at prisøkning er mer knyttet til den totale størrelsen enn rominndelingen.</li>
</ul>
<p><strong>I SLX (Spatial Lag of X) modellen kan vi tolke to utvalgte koeffisienter med tanke på den hedoniske teorien:</strong></p>
<ol type="1">
<li>Koeffisient for sqft_living (boareal):</li>
</ol>
<ul>
<li>Den direkte koeffisienten for sqft_living er positiv og svært signifikant (p-verdi &lt; 2.2e-16), noe som viser at større boareal øker boligprisen, i tråd med hedonisk teori. Den positive effekten bekrefter at boligkjøpere verdsetter større boareal.</li>
<li>Den romlige effekten (lagged sqft_living) er også negativ og signifikant (p-verdi 6.383e-09), noe som kan tyde på at økt boareal i nærområdet har en negativ effekt på boligprisen for en gitt bolig, noe som potensielt reflekterer økt konkurranse eller metning i markedet.</li>
</ul>
<ol start="2" type="1">
<li>Koeffisient for bedrooms (antall soverom):</li>
</ol>
<ul>
<li>Den direkte effekten for bedrooms er negativ og signifikant (p-verdi 2.787e-13), noe som indikerer at flere soverom kan redusere verdien når andre faktorer som boareal holdes konstant. Dette er i tråd med funn i tidligere modeller som antyder at boligkjøpere vektlegger total størrelse mer enn antall rom.</li>
<li>Den romlige effekten (lag.bedrooms) er negativ, men ikke signifikant, noe som betyr at antall soverom i nærområdet ikke har en statistisk signifikant effekt på boligprisen.</li>
</ul>
<p><strong>Ut fra resultatene for SAR-modellen kan vi tolke de implisitte prisene for to utvalgte variabler. Vi tar for oss variablene sqft_living (boareal) og bedrooms (antall soverom).</strong></p>
<ol type="1">
<li>sqft_living (boareal):</li>
</ol>
<ul>
<li>Den direkte effekten for sqft_living er positiv (ca. 273–276), noe som betyr at en økning i boareal i en enkelt bolig gir en positiv innvirkning på prisen til denne boligen. Denne effekten er i samsvar med hedonisk teori, som tilsier at større boareal gjør boligen mer verdifull og dermed øker prisen.</li>
<li>Den indirekte effekten er også positiv (ca. 114–194), noe som indikerer at økning i boareal i nærliggende boliger også har en positiv påvirkning på prisen til en gitt bolig. Dette kan skyldes at større boliger i et område gjør hele området mer attraktivt, noe som gjenspeiles i høyere priser generelt.</li>
<li>Den totale effekten (ca. 470–688) viser den samlede virkningen av både direkte og indirekte effekter, og den høye verdien bekrefter at boareal er en svært verdifull faktor i prissettingen av boliger.</li>
</ul>
<ol start="2" type="1">
<li>bedrooms (antall soverom):</li>
</ol>
<ul>
<li><p>Den direkte effekten for bedrooms er negativ (ca. -43,000 til -45,000), som betyr at et høyere antall soverom, når andre faktorer holdes konstant, kan redusere boligprisen. Dette kan tolkes som at boligkjøpere i dette markedet prioriterer boareal over antall rom, og at de kanskje foretrekker større, åpne områder fremfor flere rom.</p></li>
<li><p>Den indirekte effekten er også negativ (ca. -29,000 til -65,000), noe som antyder at flere soverom i nærliggende boliger har en negativ påvirkning på prisen til en gitt bolig. Dette kan skyldes at mange små rom i nærområdet kan indikere mindre attraktive boligtyper, som kanskje oppfattes som mindre verdifulle.</p></li>
<li><p>Den totale effekten (ca. -72,000 til -109,000) reflekterer den samlede negative virkningen av både direkte og indirekte effekter, noe som understreker at antall soverom har en mindre positiv rolle i boligprissetting sammenlignet med boareal. &gt;&gt;&gt;&gt;&gt;&gt;&gt; b15bbbfbdd1ceaf89d651f291d990edbb8a1dadf</p></li>
</ul>
</section>
<section id="konklusjon-1" class="level1">
<h1><strong>8.0 Konklusjon</strong></h1>
<p>Den hedoniske boligprismodellen gir innsikt i hvordan boligkjøpere verdsetter ulike boligelementer, og ved å anvende romlige modeller som SAR, SEM, SLX og SDEM får vi bedre forståelse av de økonomiske effektene av både lokale og globale romlige forhold. Analysene viser at boligens areal (sqft_living) er konsekvent positivt korrelert med pris, mens demografiske variabler som andel_hvit_alene kan ha både direkte og indirekte effekter avhengig av modellvalg.</p>
<p>Gjennom analysen av romlige avhengigheter i boligprisdata med modeller som OLS, SEM, SAR, SDEM og SLX, avdekkes at OLS-modellen ikke klarer å håndtere romlig autokorrelasjon, noe som fører til skjevhet i residualene. SEM og SDEM-modellene er mer effektive i å fange opp og redusere romlige effekter, med SDEM som den mest pålitelige modellen for å vurdere økonomiske effekter av både lokale og nabopåvirkninger. Selv om SLX-modellen viser en viss forbedring, er den ikke like effektiv som SEM og SDEM.</p>
<p>Evalueringen av modellene gjennom AIC og log-likelihood indikerer at SLX gir en god balanse mellom tilpasning og kompleksitet, men både SEM og SDEM gir betydelige forbedringer sammenlignet med OLS. Samlet sett understreker analysen viktigheten av å bruke romlige modeller for å oppnå mer nøyaktige og pålitelige estimater i boligmarkedet, noe som er avgjørende for informerte beslutninger og effektiv politikk.”</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-anselin1988" class="csl-entry" role="listitem">
Anselin, Luc. 1988. <em>Spatial Econometrics: Methods and Models.</em> Springer Netherlands.
</div>
<div id="ref-lesage" class="csl-entry" role="listitem">
LeSage, James P. n.d. <em>What Regional Scientists Need to Know about Spatial Econometrics</em>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>